INSERT INTO client (name) VALUES ('Fabian Bonilla');
INSERT INTO client (name) VALUES ('Milder Rodriguez');
INSERT INTO client (name) VALUES ('Fabian Hernandez');
INSERT INTO client (name) VALUES ('Maikol Conejo');
INSERT INTO client (name) VALUES ('Luis Alberto Rodríguez');
INSERT INTO client (name) VALUES ('Luis Eduardo Rodríguez');
INSERT INTO client (name) VALUES ('José Antonio Rodríguez');
INSERT INTO client (name) VALUES ('Luis Alberto González');
INSERT INTO client (name) VALUES ('Luis Eduardo Ramírez');
INSERT INTO client (name) VALUES ('Luis Alberto Sánchez');
INSERT INTO client (name) VALUES ('José Antonio Martínez');
INSERT INTO client (name) VALUES ('Luis Carlos Rodríguez');
INSERT INTO client (name) VALUES ('Luis Eduardo Gómez');
INSERT INTO client (name) VALUES ('Jaime Rodríguez');
INSERT INTO client (name) VALUES ('Alfonso Rodríguez');
INSERT INTO client (name) VALUES ('José Rodríguez');
INSERT INTO client (name) VALUES ('Rafael Rodríguez');
INSERT INTO client (name) VALUES ('Álvaro Hernández');
INSERT INTO client (name) VALUES ('Jaime Ramírez');
INSERT INTO client (name) VALUES ('Pedro Rodríguez');
INSERT INTO client (name) VALUES ('Carlos Rodríguez');
INSERT INTO client (name) VALUES ('Jaime García');
INSERT INTO client (name) VALUES ('Alfonso López');
INSERT INTO client (name) VALUES ('María del Carmen Rodríguez');
INSERT INTO client (name) VALUES ('Luz Marina Rodríguez');
INSERT INTO client (name) VALUES ('Luz Marina Sánchez');
INSERT INTO client (name) VALUES ('María del Carmen Sánchez');
INSERT INTO client (name) VALUES ('Luz Marina González');
INSERT INTO client (name) VALUES ('María del Carmen González');
INSERT INTO client (name) VALUES ('Luz Marina García');
INSERT INTO client (name) VALUES ('Luz Marina Gómez');
INSERT INTO client (name) VALUES ('María del Carmen Gómez');
INSERT INTO client (name) VALUES ('María del Carmen Hernández');
INSERT INTO client (name) VALUES ('Rosalba Rodríguez');
INSERT INTO client (name) VALUES ('María Rodríguez');
INSERT INTO client (name) VALUES ('Mercedes Rodríguez');
INSERT INTO client (name) VALUES ('María González');
INSERT INTO client (name) VALUES ('Rosalba Hernández');
INSERT INTO client (name) VALUES ('Isabel García');
INSERT INTO client (name) VALUES ('Carmen Rodríguez');
INSERT INTO client (name) VALUES ('Graciela Rodríguez');
INSERT INTO client (name) VALUES ('Cecilia Rodríguez');
INSERT INTO client (name) VALUES ('Margarita Rodríguez');
INSERT INTO client (name) VALUES ('Daniel Acevedo Jhong');
INSERT INTO client (name) VALUES ('Miguelvicente Agurto Rondoy');
INSERT INTO client (name) VALUES ('Christian Nelson Alcalá Negrón');
INSERT INTO client (name) VALUES ('Raul Eduardo Almora Hernandez');
INSERT INTO client (name) VALUES ('Jorge Alosilla Velazco Vera');
INSERT INTO client (name) VALUES ('Victor Alva Campos');
INSERT INTO client (name) VALUES ('Javier Arevalo Lopez');
INSERT INTO client (name) VALUES ('Rosario Arias Hernandez');
INSERT INTO client (name) VALUES ('Efraín Arroyo Ramírez');
INSERT INTO client (name) VALUES ('Marco Tulio Alocen Barrera');
INSERT INTO client (name) VALUES ('Cesar Baiocchi Ureta');
INSERT INTO client (name) VALUES ('Isela Flor Baylón Rojas');
INSERT INTO client (name) VALUES ('Leoncia Bedoya Castillo');
INSERT INTO client (name) VALUES ('Luz Marina Bedregal Canales');
INSERT INTO client (name) VALUES ('Ramiro Alberto Bejar Torres');
INSERT INTO client (name) VALUES ('Javier Benavides Espejo');
INSERT INTO client (name) VALUES ('Nelson Boza Solis');
INSERT INTO client (name) VALUES ('Cielito Mercedes Calle Betancourt');
INSERT INTO client (name) VALUES ('Isabel Florisa Caraza Villegas');
INSERT INTO client (name) VALUES ('Gizella Carrera Abanto');
INSERT INTO client (name) VALUES ('Estalins Carrillo Segura');
INSERT INTO client (name) VALUES ('Jorge Augusto Carrión Neira');
INSERT INTO client (name) VALUES ('Guillermo Casapia Valdivia');
INSERT INTO client (name) VALUES ('Zarita Chancos Mendoza');
INSERT INTO client (name) VALUES ('Carlos Chirinos Lacotera');
INSERT INTO client (name) VALUES ('Doris Cores Moreno');
INSERT INTO client (name) VALUES ('Maribel Corina Cortez Lozano');
INSERT INTO client (name) VALUES ('Angel Crispin Quispe');
INSERT INTO client (name) VALUES ('Antonio De Loayza Conterno');
INSERT INTO client (name) VALUES ('Ana Maria Diaz Salinas');
INSERT INTO client (name) VALUES ('Antonio Dueñas Aristisabal');
INSERT INTO client (name) VALUES ('Yuliana Espinoza Arana');
INSERT INTO client (name) VALUES ('Carlos Enrique Fernandez Guzman');
INSERT INTO client (name) VALUES ('Esther Aurora Fernandez Matta');
INSERT INTO client (name) VALUES ('Olga Ferro Salas');
INSERT INTO client (name) VALUES ('Edwin Flores Romero');
INSERT INTO client (name) VALUES ('Roberto Gamarra Astete');
INSERT INTO client (name) VALUES ('Gloria Gamio Lozano');
INSERT INTO client (name) VALUES ('Miriam García Peralta');
INSERT INTO client (name) VALUES ('Arturo Gonzales Del Valle Maguiño');
INSERT INTO client (name) VALUES ('Marlene Victoria Gonzales Huilca');
INSERT INTO client (name) VALUES ('Elsa Patricia Gonzales Medina');
INSERT INTO client (name) VALUES ('Javier Gutierrez Velez');
INSERT INTO client (name) VALUES ('Elena Rosavelt Guzman Chinag');
INSERT INTO client (name) VALUES ('Clara Guzman Quispe');
INSERT INTO client (name) VALUES ('Milagros Susan Herrera Carbajal');
INSERT INTO client (name) VALUES ('Guillermo Horruitiner Martinez');
INSERT INTO client (name) VALUES ('Lourdes Huamani Flores');
INSERT INTO client (name) VALUES ('Luis Armando Huapaya Raygada');
INSERT INTO client (name) VALUES ('Marcos Huarcaya Quispe');
INSERT INTO client (name) VALUES ('Walter David Huaytan Sauñe');
INSERT INTO client (name) VALUES ('Elba Mercedes La Rosa Fabian');
INSERT INTO client (name) VALUES ('Pedro Guillermo Landa Ginocchio');
INSERT INTO client (name) VALUES ('Roberto Julian Llaja Tafur');
INSERT INTO client (name) VALUES ('Orfelina Llenpen Nuñez');
INSERT INTO client (name) VALUES ('Hector Lujan Venegas');
INSERT INTO client (name) VALUES ('Gissela Maguiña San Yen Man');
INSERT INTO client (name) VALUES ('Cosme Adolfo Maldonado Quispe');
INSERT INTO client (name) VALUES ('Sandra Monica Maldonado Tinco');
INSERT INTO client (name) VALUES ('Jenny Maria Mallqui Celestino');
INSERT INTO client (name) VALUES ('Santiago Mamani Uchasara');
INSERT INTO client (name) VALUES ('Magda Janeth Maravi Navarro');
INSERT INTO client (name) VALUES ('Martin Martinez Marquez');
INSERT INTO client (name) VALUES ('Oscar Enrique Medina Zuta');
INSERT INTO client (name) VALUES ('Carlos P Melgarejo Vibes');
INSERT INTO client (name) VALUES ('Elizabeth Miguel Holgado');
INSERT INTO client (name) VALUES ('Manuel Antonio Mori Ramirez');
INSERT INTO client (name) VALUES ('Carlos Alberto Nuñez Huayanay');
INSERT INTO client (name) VALUES ('Olga Ore Reyes');
INSERT INTO client (name) VALUES ('Josue Orrillo Ortiz');
INSERT INTO client (name) VALUES ('Josué Victor Orrillo Ortiz');
INSERT INTO client (name) VALUES ('Carmen Rosa Pardave Camacho');
INSERT INTO client (name) VALUES ('Santiago Victor Paredes Jaramillo');
INSERT INTO client (name) VALUES ('Arturo Pastor Porras');
INSERT INTO client (name) VALUES ('Enrique Pinedo Nuñez');
INSERT INTO client (name) VALUES ('Sonia Prada Vilchez');
INSERT INTO client (name) VALUES ('Gerardo David Riega Calle');
INSERT INTO client (name) VALUES ('Freddy Rios Lima');
INSERT INTO client (name) VALUES ('Teresa Rios Lima');
INSERT INTO client (name) VALUES ('Juan Elvis Riquelme Miranda');
INSERT INTO client (name) VALUES ('Georgina Esperanza Roa Yanac');
INSERT INTO client (name) VALUES ('Rosa Liliana Robles Valverde');
INSERT INTO client (name) VALUES ('Rosa Josefa Rodriguez Farias');
INSERT INTO client (name) VALUES ('Maria De Fatima Rojas Valdivia');
INSERT INTO client (name) VALUES ('Rosa Maria Romero Gomez Sanchez');
INSERT INTO client (name) VALUES ('Carina Magnolia Rosales Flores');
INSERT INTO client (name) VALUES ('Carlos Jose Rosas Bonifaz');
INSERT INTO client (name) VALUES ('Aida Cristina Ruiz De Castilla Britto');
INSERT INTO client (name) VALUES ('Celin Salcedo Del Pino');
INSERT INTO client (name) VALUES ('Violeta Marilu Salinas Puccio');
INSERT INTO client (name) VALUES ('Augusto Sanchez Arone');
INSERT INTO client (name) VALUES ('Pedro Manuel Santa Cruz Benssa');
INSERT INTO client (name) VALUES ('Angel Solano Vargas');
INSERT INTO client (name) VALUES ('Jose Alberto Tejedo Luna');
INSERT INTO client (name) VALUES ('Angel Tenorio Davila');
INSERT INTO client (name) VALUES ('Miguel Angel Torres Gaspar');
INSERT INTO client (name) VALUES ('Jacquelin Trujillo Parodi');
INSERT INTO client (name) VALUES ('Ruth Noricila Vega Carreazo');
INSERT INTO client (name) VALUES ('Guillermo Jonathan Velasquez Ramos');
INSERT INTO client (name) VALUES ('Alejandro Vera Silva');
INSERT INTO client (name) VALUES ('Blanca Katty Vilca Lucero');
INSERT INTO client (name) VALUES ('Enrique Godofredo Vilgoso Alvarado');
INSERT INTO client (name) VALUES ('Cecilia Yamawaki Onaga');
INSERT INTO client (name) VALUES ('Mariela Milagros Zamalloa Vega');
INSERT INTO client (name) VALUES ('Monica Zapata Chang');
INSERT INTO client (name) VALUES ('Juan Carlos Zegarra Salcedo');
INSERT INTO client (name) VALUES ('Hilrich Mariela Zu Flores');